### ISSUE TITLE
Include additional functions to be triggered on error?

### ISSUE THREAD

**Issue by stevepowell99** [daattali/shinydisconnect#11]
Hi, when a disconnect occurs (due to fatal error or timeout) I would like to also write at least the time, URL etc to a log. Is there any way to include an additional function, say within disconnectmessage(), eg myFunctionToWriteTheErrorToAFile() ? So that the user would still see the disconnect message but at least some basic information would be written to a file?

**Comment by daattali** [comment]
Unfortunately I don't think there's a reliable way to do this. Everything that happens in this package is entirely on the client side, because once there is a disconnection, you can no longer pass messages between the client (browser) and the server (R/shiny).

**Comment by stevepowell99** [comment]
👍🏽
