### ISSUE TITLE
enhancement - link to website

### ISSUE THREAD

**Issue by mattapel** [daattali/shinydisconnect#12]
Hi there,
thanks for this great package!
I tried to use your code in app on shiny server open source to route users back to a log in website. 
Therefore I adjusted your utils.R, simply trying to add a link.
Strangely, it still only reloads, even if I remove "onclick="window.location.reload(true);"  replace with onclick="window.location='https://www....';" or just add a link to href.
Is this somehow hardcoded on the side of shiny server ?

**Comment by daattali** [comment]
That should work. I just tried it, I changed this line https://github.com/daattali/shinydisconnect/blob/1e245f0179b8a43d21ca85687ed53389fbfd4b91/R/utils.R#L17

to 

```r
htmltools::tags$a(id="ss-reload-link", href="#", onclick="window.location='https://github.com/daattali/shinydisconnect/issues/12';")
```

And then ran the example app:

```r
  shinyApp(
    ui = fluidPage(
      disconnectMessage(),
      actionButton("disconnect", "Disconnect the app")
    ),
    server = function(input, output, session) {
      observeEvent(input$disconnect, {
        session$close()
      })
    }
  )
```

And when the app gets disconnected and I click the Refresh button, it goes to the new URL.
