### ISSUE TITLE
WAVE flags refresh links in custom disconnect messages as having no link text

### ISSUE THREAD

**Issue by BajczA475** [daattali/shinydisconnect#13]
I have a custom disconnect message for my app using this awesome package, as follows:

```
disconnectMessage(text = "Hmm...something has gone wrong. Either you have been idle for too long and the app has timed out or an error has been triggered in the R code of the application. To try again, refresh the page. If, after doing so, you encounter this page again after taking the same actions as before, please file a bug report with Alex at bajcz003@umn.edu. We appreciate your cooperation!", 
                    refresh = "Refresh the page", 
                    width = "full", 
                    top = "center", 
                    size = 22, 
                    background = "#7a0019", 
                    colour = "white", 
                    refreshColour = "#ffb71e", 
                    css = "z-index: 100000 !important;"),
```
                    
Though I've specified text for the refresh link using the _refresh_ parameter (see above), and this text is clearly visible when the message displays upon disconnect, the WAVE accessibility-checking plug-in still flags this link as containing no text:

![image](https://github.com/user-attachments/assets/9d941392-6245-4683-8745-395d557cd3d9)

The tool then references the following code as evidence:
```
<div id="ss-connect-dialog">
<a id="ss-reload-link" href="#" onclick="window.location.reload(true);"></a>
</div>

```
And when I use devtools to inspect the link element, it indeed has nothing in it. I actually can't figure out where the "Refresh the page" is coming from, within the DOM. I would guess it's injected via JS but I'm not sure. 

What's more interesting is that the link is apparently in the DOM even prior to disconnect. WAVE knows it isn't visible, but flags it as empty anyway. 

With an assist or two from ChatGPT, I was able to figure out that I could use CSS and JS to ensure the link contains text at all times:

```
tags$head(
  tags$script(HTML("
      $(document).ready(function() {
      var reloadLink = document.getElementById('ss-reload-link');
      if (reloadLink) {
        reloadLink.innerText = 'Refresh the page';
       }
      });
    "))
),
```

This did satisfy WAVE--it no longer thinks the link is empty before or after disconnect and it doesn't affect when or how it becomes visible. It'd be nice if there were an easier way to ensure this link is compliant though!

**Comment by daattali** [comment]
The reason you don't see the text in the DOM is because I use the `:before` pseudoelement with a `content` css field to populate the text. I might seem odd, but by avoiding javascript it works cleanly and it works on all cases that I tested. Using javascript was a lot messier in some circumstances.

Unfortunately using the pseudoelement is indeed not accessible. I did not think of that when I created this package, and it is a limitation I'll need to live with. I do appreciate your input though.

**Comment by BajczA475** [comment]
I see--no need to re-open this or reconsider it in any way! I had just had our app audited by our University's Digital Accessibility center, and they had also noted that the disconnect message does not move focus or become focusable, and that the text message on it also is in a content css field, so these are things we can't abide and still meet new Digital Accessibility requirements coming from the US federal government. 

If anyone else is in the same boat as us, FWIW, this JS from ChatGPT works well for our app:

tags$script(HTML("
  $(document).on('shiny:disconnected', function(event) {
    var el = document.getElementById('ss-connect-dialog');
    if (el) {
      // Create an accessible alert
      var msgContainer = document.createElement('div');
      msgContainer.textContent = 'XXX'; //PUT YOUR MESSAGE HERE.
      msgContainer.setAttribute('role', 'alertdialog');
      msgContainer.setAttribute('tabindex', '-1');
      msgContainer.setAttribute('aria-label', 'Error message');
      msgContainer.style.outline = 'none';
      msgContainer.style.marginBottom = '1em';

      // Insert it at the beginning of the disconnect dialog
      el.insertBefore(msgContainer, el.firstChild);

      // Shift focus
      msgContainer.focus();
      
      // MAKE SURE THAT THE DISCONNECT LINK ALSO HAS TEXT IN IT:
      $(document).ready(function() {
      var reloadLink = document.getElementById('ss-reload-link');
      if (reloadLink) {
        reloadLink.innerText = 'Refresh the page';
       }
      });
    }
  });
"))

Can't promise it'll work for everyone though!
