### ISSUE TITLE
Different messages for error and session timeout?

### ISSUE THREAD

**Issue by sarthi2395** [daattali/shinydisconnect#2]
This is not an issue as such, however, I was thinking it would be nice to have separate disconnect functions, one for errors and another one for session timeouts. Right now, if I customize the disconnect message for timeout, it doesn't look meaningful for the users when the app stops because of an error that had occurred and vice versa.

**Comment by daattali** [comment]
I don't think this will be possible with the package, because the package can only take care of the UI aspect of the disconnection. I have no way of knowingwhat caused the disconnection unfortunately.

**Comment by daattali** [comment]
To be clear, I 100% agree that would be useful, but it's simply not possible because this package styles the disconnection message, and the disconnection happens when an error OR a timeout happens, but we can't know which one happened. All we know is that something caused a disconnect.

**Comment by sarthi2395** [comment]
Ah, understood. Thank you! Great package indeed :)
