### ISSUE TITLE
Include Href in Text

### ISSUE THREAD

**Issue by Jonas2019** [daattali/shinydisconnect#3]
Hi There,

First I have to say that this is great work! I really enjoyed this package.
I am making a web app in shiny and I just wonder is it possible to do something like : disconnectMessage(text = HTML("<strong href:blah blah> Raw HTML</strong>")).
Right now it will not look at the strong tag and produce some other symbols in the popup window.

I think that this will be very useful for people using this package because they can include a link such as a feedback form once their users encounter a disconnect.

**Comment by daattali** [comment]
I agree it would be very useful. Unfortunately HTML cannot be supported, only plain text. I did hope for being able to include HTML when I built the package, but it's not possible (content field in css is used for technical reasons, and it only supports plaintext https://stackoverflow.com/questions/4505093/css-content-property-is-it-possible-to-insert-html-instead-of-text)
