### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by r0bis** [daattali/shinydisconnect#4]
There seems to be an error that prevents application from loading if I insert in UI section.
```
    ui <- dashboardPage(
    disconnectMessage2(),
   further elements(...),
```
Then upon loading this happens:

 ```
<script>$(function() {  $(document).on('shiny:disconnected', function(event) {    $('#ss-connect-dialog').show();    $('#ss-overlay').show();  })});</script>
<div id="ss-connect-dialog" style="display: none;">
  <a id="ss-reload-link" href="#" onclick="window.location.reload(true);"></a>
</div>
<div id="ss-overlay" style="display: none;"></div>
Error in tagAssert(header, type = "header", class = "main-header") : 
  Expected an object with class 'shiny.tag'.
```

And nothing loads. What could this mean? Thanks.

**Comment by daattali** [comment]
The first argument of dashboardPage is a header.  You can't put any UI as the first argument. It has to go inside the dadhboardBody

**Comment by r0bis** [comment]
Thanks a lot, that's good to know. It works if I put it in dashboard body:

```
dashboardBody(
        shinyDashboardThemes(
            theme = "grey_light" 
        ),
        disconnectMessage2()

```

**Comment by daattali** [comment]
This is true for anything you put in UI, not just this package

**Comment by r0bis** [comment]
Sorry, I did not know that; I thought - dashboardHeader is still inside the
page <body> tags and therefore not too different  from any other part of
the visible page.
Roberts
--
Dr Roberts Klotins

**Comment by bcaessens** [comment]
Just for those who run into similar issues, I think this is related: 

`ui <- navbarPage(disconnectMessage(...),...,tabPanel())
`
If you put disconnectMessage in the navbarPage outside of a tabPanel, you will see a hidden tab-output. In fact, there will be something like tab-9400-3 in the UI. 
When you put the disconnectMessage() inside a tabPanel definition, everything is fine. 

Kind regards,
Bernie.

**Comment by daattali** [comment]
Yes that's the same issue, thank you. There are countless other similar examples. The important takeaway is to look at the arguments that a UI function takes and make sure to place the correct items in the correct places (this applies to any shiny UI function, not just to this package)

**Comment by bcaessens** [comment]
Hi Dean,

Thanks for this and your other great packages. And of course you are absolutely right. I just came across this elegant solution, that in my case seems to work just fine: wrap the ui in a tagList and put disconnectMessage as the first element, like this: 

ui <- tagList(disconnectMessage(...), navbarPage(...rest of ui)). In modularized shiny code, this gives me the beautiful disconnect message out of the box on all my modules (tabs). 

Cheers,
Bernie.

**Comment by daattali** [comment]
Yep that's the advise I've been giving in shinyjs for years https://deanattali.com/shinyjs/advanced#usage-navbarpage
Knowing about `tagList()` is a very useful thing, comes in handy very often in shiny!
