### ISSUE TITLE
Feature request: Show error details

### ISSUE THREAD

**Issue by pepijn-devries** [daattali/shinydisconnect#8]
Thank you for this package, very useful. Not sure if it's possible, I've been looking all over for this: is it possible to display a message that shows the cause for disconnecting from the Shiny server? Preferably with a stack trace to the error. This will make it easier for users of an app to file a bug report, and for the developer to fix the problem.

The problem is probably that once the app is disconnected, you can’t get any information from the server, apart from what is been send to ‘event.socket’ by ‘shiny:disconnected’ to the client side (javascript). From what I could tell, this socket appears empty after a crash. Maybe you have some fresh ideas?

Thanks in advance!

**Comment by daattali** [comment]
I may be wrong, but from what I know this isn't possible

**Comment by pepijn-devries** [comment]
After some digging, I've found this blog post:
https://www.r-bloggers.com/2018/02/adding-logging-to-a-shiny-app-with-loggit/

Maybe it is possible send the error-log file with 'addCustomMessageHandler' to javascript with the call to session$onSessionEnded. When I've got something working, I will try to send a minimal example.

**Comment by daattali** [comment]
I suspect that after the session has ended, you won't be able to send messages from shiny to javacript anymore because the connection has been severed.

**Comment by pepijn-devries** [comment]
I think you are right. I haven't gotten it to work. Will let you know when I find a way in the future. Thank you for your time. I will close this issue...
